-- Schema Supabase pour le portfolio photo
-- Compatible avec le code actuel : catégories, photos, page À propos, et bucket public "photos"

create extension if not exists "pgcrypto";

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  image text,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.photos (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  filename text not null unique,
  category text not null references public.categories(slug) on update cascade on delete restrict,
  created_at timestamptz not null default now()
);

create table if not exists public.about (
  id bigint generated by default as identity primary key,
  title text not null,
  image text not null,
  content_1 text not null,
  content_2 text not null,
  content_3 text not null,
  created_at timestamptz not null default now()
);

-- Compatibilite avec une base existante creee avant l'ajout de ces colonnes.
alter table public.categories add column if not exists image text;
alter table public.categories add column if not exists description text;
alter table public.photos add column if not exists description text;

create index if not exists idx_categories_slug on public.categories (slug);
create index if not exists idx_photos_category on public.photos (category);
create index if not exists idx_photos_created_at on public.photos (created_at desc);

alter table public.categories enable row level security;
alter table public.photos enable row level security;
alter table public.about enable row level security;

drop policy if exists "Categories are viewable by everyone" on public.categories;
drop policy if exists "Photos are viewable by everyone" on public.photos;
drop policy if exists "About is viewable by everyone" on public.about;
drop policy if exists "Allow custom admin writes on categories" on public.categories;
drop policy if exists "Allow custom admin updates on categories" on public.categories;
drop policy if exists "Allow custom admin deletes on categories" on public.categories;
drop policy if exists "Allow custom admin writes on photos" on public.photos;
drop policy if exists "Allow custom admin updates on photos" on public.photos;
drop policy if exists "Allow custom admin deletes on photos" on public.photos;
drop policy if exists "Allow custom admin writes on about" on public.about;
drop policy if exists "Allow custom admin updates on about" on public.about;
drop policy if exists "Allow custom admin deletes on about" on public.about;

create policy "Categories are viewable by everyone"
on public.categories
for select
using (true);

create policy "Photos are viewable by everyone"
on public.photos
for select
using (true);

create policy "About is viewable by everyone"
on public.about
for select
using (true);

-- IMPORTANT : dans cette version, l'admin est protégé par un mot de passe custom côté Next.js,
-- donc Supabase ne voit pas un utilisateur authentifié via auth.role().
-- Pour que le front avec la clé anon puisse écrire, on autorise les inserts/updates/deletes.
create policy "Allow custom admin writes on categories"
on public.categories
for insert
with check (true);

create policy "Allow custom admin updates on categories"
on public.categories
for update
using (true);

create policy "Allow custom admin deletes on categories"
on public.categories
for delete
using (true);

create policy "Allow custom admin writes on photos"
on public.photos
for insert
with check (true);

create policy "Allow custom admin updates on photos"
on public.photos
for update
using (true);

create policy "Allow custom admin deletes on photos"
on public.photos
for delete
using (true);

create policy "Allow custom admin writes on about"
on public.about
for insert
with check (true);

create policy "Allow custom admin updates on about"
on public.about
for update
using (true);

create policy "Allow custom admin deletes on about"
on public.about
for delete
using (true);

-- Bucket public pour les fichiers de galerie
insert into storage.buckets (id, name, public)
values ('photos', 'photos', true)
on conflict (id) do nothing;

drop policy if exists "Public read access to photos bucket" on storage.objects;
drop policy if exists "Custom admin upload to photos bucket" on storage.objects;
drop policy if exists "Custom admin update on photos bucket" on storage.objects;
drop policy if exists "Custom admin delete on photos bucket" on storage.objects;

create policy "Public read access to photos bucket"
on storage.objects
for select
using (bucket_id = 'photos');

create policy "Custom admin upload to photos bucket"
on storage.objects
for insert
with check (bucket_id = 'photos' and true);

create policy "Custom admin update on photos bucket"
on storage.objects
for update
using (bucket_id = 'photos' and true);

create policy "Custom admin delete on photos bucket"
on storage.objects
for delete
using (bucket_id = 'photos' and true);
